"""FastAPI app exposing the Lost Assets search endpoint.

Run locally:
    python -m app.ingestion.seed          # populate SQLite with mock data
    uvicorn app.main:app --reload

Phase 1 scope: search + matching only. No outreach, contracts, fee
collection, or paid-filing workflow is implemented or exposed here — those
require separate legal sign-off per state and come in a later phase.
"""
from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from pydantic import BaseModel, Field

from app.db import connect, init_db, DB_PATH
from app.matching.engine import match_type_a, match_type_b

app = FastAPI(
    title="Lost Assets Search API",
    description="Phase 1: free search/matching against unclaimed-property and dissolved-business data. No outreach or filing workflow.",
    version="0.1.0",
)


@app.on_event("startup")
def _ensure_db() -> None:
    init_db()
    if not Path(DB_PATH).exists():
        raise RuntimeError("Database file missing after init_db(); check app/db.py")


class SearchRequest(BaseModel):
    name: str = Field(..., min_length=2, description="Full name to search, e.g. 'Robert Johnson'")
    state: str | None = Field(None, min_length=2, max_length=2, description="Optional 2-letter state code to weight/filter results, e.g. 'WA'")


class SearchResponse(BaseModel):
    query: dict
    type_a_matches: list[dict]
    type_b_matches: list[dict]
    disclaimer: str


DISCLAIMER = (
    "Results are possible matches from public unclaimed-property and business-entity "
    "records, generated by automated name matching. They are not verified claims and "
    "are not legal or financial advice. Confidence tiers (high/medium/low) reflect name-"
    "match strength only, including low-confidence 'possible but unverified' matches. "
    "Verify any match directly with the listed state agency before taking action."
)


@app.post("/lost-assets/search", response_model=SearchResponse)
def search(req: SearchRequest) -> SearchResponse:
    state = req.state.upper() if req.state else None
    with connect() as conn:
        type_a = match_type_a(req.name, state, conn)
        type_b = match_type_b(req.name, state, conn)

    return SearchResponse(
        query={"name": req.name, "state": state},
        type_a_matches=[m.to_dict() for m in type_a],
        type_b_matches=[m.to_dict() for m in type_b],
        disclaimer=DISCLAIMER,
    )


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}
