import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — GetScrewedScore',
  description: 'Terms and conditions for using GetScrewedScore.',
  robots: { index: true, follow: true },
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-black text-brand-text">{title}</h2>
      <div className="text-sm text-brand-sub leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  const updated = 'March 29, 2026'

  return (
    <div className="min-h-screen bg-brand-bg">
      {/* Nav */}
      <nav className="border-b border-brand-border/60 bg-brand-bg/80 backdrop-blur-xl">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-1 select-none">
            <span className="text-base font-black text-brand-text">Get</span>
            <span className="text-base font-black" style={{
              background: 'linear-gradient(135deg, #ff6b60, #ff3b30)',
              WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
            }}>Screwed</span>
            <span className="text-base font-black text-brand-text">Score</span>
          </Link>
          <Link href="/" className="text-xs text-brand-sub hover:text-brand-text transition-colors">
            ← Back to app
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 py-16 space-y-10">
        {/* Header */}
        <div className="space-y-3">
          <h1 className="text-4xl font-black text-brand-text tracking-tight">Terms of Service</h1>
          <p className="text-sm text-brand-sub">Last updated: {updated}</p>
          <p className="text-sm text-brand-sub leading-relaxed">
            By accessing or using <strong className="text-brand-text">GetScrewedScore</strong> at{' '}
            <a href="https://screwedscore.com" className="text-red-400 hover:underline">screwedscore.com</a>
            , you agree to be bound by these Terms of Service. If you do not agree, do not use the service.
          </p>
        </div>

        <div className="w-full h-px bg-brand-border" />

        <Section title="1. The Service">
          <p>GetScrewedScore is an AI-powered document analysis tool that helps users identify potential overcharges, suspicious fees, and concerning clauses in bills, invoices, and contracts. The service is operated by REMbyDesign.</p>
          <p>Results are generated by AI and are provided for <strong className="text-brand-text">informational purposes only</strong>. GetScrewedScore is not a law firm, financial advisor, or medical billing specialist. Nothing produced by this service constitutes legal, financial, or professional advice.</p>
        </Section>

        <Section title="2. Not Legal or Financial Advice">
          <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-4 space-y-2">
            <p className="font-bold text-yellow-400 text-xs uppercase tracking-wider">Important Disclaimer</p>
            <p>GetScrewedScore&apos;s AI analysis is not a substitute for professional legal or financial advice. Analysis results may be incomplete, inaccurate, or not applicable to your specific situation.</p>
            <p>Before taking any action based on our analysis — including disputing a charge, renegotiating a contract, or refusing to pay — consult a qualified professional (attorney, financial advisor, or relevant specialist).</p>
            <p>REMbyDesign is not responsible for any decisions you make based on results from this service.</p>
          </div>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree to use GetScrewedScore only for lawful purposes. You may not:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Upload documents you do not own or have authorization to share</li>
            <li>Upload documents containing sensitive personal information of others without their consent</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the service</li>
            <li>Use the service to generate false, misleading, or defamatory content</li>
            <li>Circumvent rate limits or access controls through automated means</li>
            <li>Use the service for any illegal purpose</li>
          </ul>
        </Section>

        <Section title="4. Free Tier and Pro Subscription">
          <p><strong className="text-brand-text">Free tier.</strong> Unregistered users may perform up to 2 document analyses per 24-hour period per IP address. Free results include the full AI analysis.</p>
          <p><strong className="text-brand-text">Pro subscription.</strong> For $9.99/month, Pro subscribers receive unlimited analyses, priority processing, the viral content generator, and auto-generated video creation. Pro subscriptions are billed monthly and can be cancelled at any time.</p>
          <p><strong className="text-brand-text">Refunds.</strong> We offer a full refund within 7 days of your first charge if you are not satisfied. Contact us at <a href="mailto:support@rembydesign.com" className="text-red-400 hover:underline">support@rembydesign.com</a>. After 7 days, charges are non-refundable but you may cancel at any time to stop future billing.</p>
          <p><strong className="text-brand-text">Cancellation.</strong> Cancel your Pro subscription at any time through your Stripe billing portal. You will retain Pro access until the end of your current billing period.</p>
        </Section>

        <Section title="5. Intellectual Property">
          <p><strong className="text-brand-text">Your documents.</strong> You retain full ownership of any documents you upload. By uploading a document, you grant REMbyDesign a limited, non-exclusive license to process the document solely to provide the analysis service.</p>
          <p><strong className="text-brand-text">Our service.</strong> The GetScrewedScore platform, branding, code, and AI prompts are the intellectual property of REMbyDesign. You may not copy, reproduce, or redistribute any part of the service without written permission.</p>
          <p><strong className="text-brand-text">Generated content.</strong> AI-generated analysis results, scripts, and videos produced by the service are yours to use for personal and commercial purposes (e.g., posting to social media).</p>
        </Section>

        <Section title="6. Privacy">
          <p>Our collection and use of personal information is described in our <Link href="/privacy" className="text-red-400 hover:underline">Privacy Policy</Link>, which is incorporated into these Terms by reference.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>To the maximum extent permitted by law, REMbyDesign and its officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of GetScrewedScore — including but not limited to financial losses, legal disputes, or decisions made based on AI analysis results.</p>
          <p>Our total liability for any claim arising from your use of the service is limited to the amount you paid us in the 30 days prior to the claim, or $10, whichever is greater.</p>
        </Section>

        <Section title="8. Disclaimer of Warranties">
          <p>GetScrewedScore is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or that AI analysis results will be accurate or complete.</p>
        </Section>

        <Section title="9. Changes to the Service">
          <p>We reserve the right to modify, suspend, or discontinue any part of the service at any time without notice. We may also update these Terms. Continued use of the service after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="10. Governing Law">
          <p>These Terms are governed by the laws of the United States. Any disputes arising from these Terms or the service will be resolved through binding arbitration in accordance with the American Arbitration Association&apos;s rules, except that either party may seek injunctive relief in a court of competent jurisdiction.</p>
        </Section>

        <Section title="11. Contact">
          <p>Questions about these Terms? Contact us:</p>
          <div className="rounded-xl border border-brand-border bg-brand-surface p-4 space-y-1">
            <p><strong className="text-brand-text">REMbyDesign</strong></p>
            <p>Email: <a href="mailto:support@rembydesign.com" className="text-red-400 hover:underline">support@rembydesign.com</a></p>
            <p>Website: <a href="https://screwedscore.com" className="text-red-400 hover:underline">screwedscore.com</a></p>
          </div>
        </Section>

        <div className="pt-4 border-t border-brand-border flex items-center justify-between text-xs text-brand-sub/50">
          <span>© {new Date().getFullYear()} REMbyDesign. All rights reserved.</span>
          <Link href="/privacy" className="hover:text-brand-text transition-colors">Privacy Policy →</Link>
        </div>
      </main>
    </div>
  )
}
