export const RESPONSES: Record<string, string> = {
  F1: "Friendly reminder Chat: Please don't spam multiple messages in chat. Thank you 🙏",
  F2: "Yes, we do ship worldwide. 🌍",
  F3: "Are you curious about the price of a card? Head on over to the Collectr app or TCG for your price reference. Thank you",
  F4: "Are you curious about the price of a pack/order? Head on over to the shop http://www.poke-bank.com",
  F5: "Chat just another friendly reminder — let's keep the chat clean and clear of any foul language. This is a family friendly stream. Thank you for understanding. 🙏",
  F6: "Curious how this works? You place an order for cards on our website, we then place you into a live queue (times vary). Orders are opened live and then shipped to your address.",
  F7: "How long will it take to receive my cards? You can expect roughly 3–5 days in the US and 7–10 days overseas. (times may vary)",
  F8: "Chat you heard the man CLOVERS IN 🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀",
  F9: "Chat: For safety of all users we request that you do not ask other people for personal information. Thank you for understanding. 🙏",
  F10: "Looking to place an order but don't know how? Head on over to our website at http://www.poke-bank.com and get your packs there.",
  F11: "Reminder: once you place an order you will be placed into a queue (times vary) and your orders will be ripped accordingly.",
  F12: "Disagree with the price? Feel free to shop around. When you purchase with us you buy the experience and the community — that is second to none. 💪",
  F13: "Curious how we get our packs? This is a Shop/LLC — we receive our products from distribution.",
  F14: "Have an issue? Please reach out to support@poke-bank.com. Response times vary due to volume of emails and limited staff. Expect a response within 1–3 days.",
  F15: "Friendly Reminder CHAT: No free packs are available here. But you can go to TikTok and enter there (US only — their rules, not ours), or alternatively Discord for a weekly worldwide giveaway.",
};
