import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import type { AnalysisResult } from '@/lib/types'
import { DOCUMENT_TYPE_LABELS } from '@/lib/types'

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export const runtime = 'nodejs'

// netlify.toml caps every function at 26s. This route used to declare
// maxDuration = 60, which the platform simply ignored — a 4096-token document
// generation regularly ran past 26s and Netlify killed the invocation, so the
// client got a 502 HTML page and `res.json()` blew up on the leading '<'.
// The response is now streamed, so bytes reach the browser within a second or
// two and the document renders progressively instead of waiting on one big
// JSON payload.
export const maxDuration = 26

const SYSTEM_PROMPT = `You are a professional document rewriter. You receive an AI analysis of a flawed document and produce a corrected, professional version.

Rules:
- Output ONLY the inner body HTML — no <html>, <head>, or <body> tags, and no markdown code fences (no \`\`\`) wrapping the output
- Use inline styles only — no external CSS or class-based styling
- Typography: font-family: Georgia, serif; color: #111; line-height: 1.6
- Max width: 720px, margin: auto, padding: 40px
- Headings: bold, 18px for title, 14px for sections
- Tables: full width, border-collapse: collapse, thin 1px #ccc borders, cell padding 8px
- Signature blocks: two-column flex layout with underline lines and date fields
- Fix every flagged issue using the suggested fix or industry-standard language
- Replace overcharged amounts with fair market values from the industry context
- Add missing protections and clauses that were flagged as absent
- Rewrite risky or vague clauses with clear, fair language
- Remove duplicate charges
- The result must be a complete, ready-to-use professional document
- Add a footer: "Corrected document generated by GetScrewedScore.com — review with a qualified professional before use" in small gray text
- Do NOT add a disclaimer inside the document body itself beyond the footer`

function buildUserMessage(result: AnalysisResult): string {
  const docLabel = DOCUMENT_TYPE_LABELS[result.document_type] ?? result.document_type

  const flagSummary = (result.top_findings ?? []).map((f, i) => {
    const lines = [
      `Issue ${i + 1} [${f.severity.toUpperCase()} — ${f.category}]: ${f.title}`,
      `  Problem: ${f.description}`,
    ]
    if (f.original_text)  lines.push(`  Original text: "${f.original_text}"`)
    if (f.suggested_fix)  lines.push(`  Suggested fix: ${f.suggested_fix}`)
    if (f.dollar_impact)  lines.push(`  Dollar impact: $${f.dollar_impact.toFixed(2)}`)
    return lines.join('\n')
  }).join('\n\n')

  let lineItemCorrections = ''
  if (result.overcharge?.line_items?.length) {
    lineItemCorrections = '\n\nLINE ITEM CORRECTIONS:\n' + result.overcharge.line_items.map(item =>
      item.flagged
        ? `- "${item.description}": was $${item.charged_amount} — ${item.flag_reason}. Industry context: ${item.industry_context ?? 'use fair market rate'}`
        : `- "${item.description}": $${item.charged_amount} (OK — keep as-is)`
    ).join('\n')
  }

  let clauseFixes = ''
  if (result.contract_guard?.red_flags?.length) {
    clauseFixes = '\n\nCLAUSE FIXES:\n' + result.contract_guard.red_flags
      .filter((f: { alternative_language?: string; clause_text?: string }) => f.alternative_language)
      .map((f: { alternative_language?: string; clause_text?: string }) => `- Replace "${f.clause_text}" with: "${f.alternative_language}"`)
      .join('\n')
  }

  return `Fix this ${docLabel}.

ANALYSIS SUMMARY:
Score: ${result.screwed_score} (${result.screwed_score_percent}% screwed)
${result.plain_summary}

FLAGS TO FIX:
${flagSummary}
${lineItemCorrections}
${clauseFixes}

Generate a complete corrected ${docLabel} that resolves every issue above. Use placeholder fields (___________) for any personal information not provided. Make it look professional and ready to print.`
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null)
  if (!body?.result) {
    return NextResponse.json({ error: 'Missing analysis result' }, { status: 400 })
  }

  const userMessage = buildUserMessage(body.result as AnalysisResult)
  const encoder = new TextEncoder()

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const ai = client.messages.stream({
          model: 'claude-sonnet-4-6',
          max_tokens: 4096,
          system: SYSTEM_PROMPT,
          messages: [{ role: 'user', content: userMessage }],
        })

        for await (const event of ai) {
          if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
            controller.enqueue(encoder.encode(event.delta.text))
          }
        }
        controller.close()
      } catch (err) {
        // The client can't read a status code once streaming has begun, so
        // failures are surfaced as a sentinel it can detect in the body.
        const msg =
          err instanceof Anthropic.RateLimitError ? 'Rate limited — try again in a moment.'
          : err instanceof Anthropic.APIError     ? `AI service error (${err.status}).`
          : 'Could not generate the document.'
        console.error('[fix-document] generation failed:', err)
        controller.enqueue(encoder.encode(`\n<!--GSS_ERROR:${msg}-->`))
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Accel-Buffering': 'no',
    },
  })
}
