import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import type { AnalysisResult } from '@/lib/types'
import { DOCUMENT_TYPE_LABELS } from '@/lib/types'

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export const runtime = 'nodejs'
export const maxDuration = 60

const SYSTEM_PROMPT = `You are a professional document rewriter. You receive an AI analysis of a flawed document and produce a corrected, professional version.

Rules:
- Output ONLY the inner body HTML — no <html>, <head>, or <body> tags
- Use inline styles only — no external CSS or class-based styling
- Typography: font-family: Georgia, serif; color: #111; line-height: 1.6
- Max width: 720px, margin: auto, padding: 40px
- Headings: bold, 18px for title, 14px for sections
- Tables: full width, border-collapse: collapse, thin 1px #ccc borders, cell padding 8px
- Signature blocks: two-column flex layout with underline lines and date fields
- Fix every flagged issue using the suggested fix or industry-standard language
- Replace overcharged amounts with fair market values from the industry context
- Add missing protections and clauses that were flagged as absent
- Rewrite risky or vague clauses with clear, fair language
- Remove duplicate charges
- The result must be a complete, ready-to-use professional document
- Add a footer: "Corrected document generated by GetScrewedScore.com — review with a qualified professional before use" in small gray text
- Do NOT add a disclaimer inside the document body itself beyond the footer`

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null)
  if (!body?.result) {
    return NextResponse.json({ error: 'Missing analysis result' }, { status: 400 })
  }

  const result = body.result as AnalysisResult
  const docLabel = DOCUMENT_TYPE_LABELS[result.document_type] ?? result.document_type

  // Build a structured summary of every flag and its fix
  const flagSummary = result.top_findings.map((f, i) => {
    const lines = [
      `Issue ${i + 1} [${f.severity.toUpperCase()} — ${f.category}]: ${f.title}`,
      `  Problem: ${f.description}`,
    ]
    if (f.original_text) lines.push(`  Original text: "${f.original_text}"`)
    if (f.suggested_fix) lines.push(`  Suggested fix: ${f.suggested_fix}`)
    if (f.dollar_impact) lines.push(`  Dollar impact: $${f.dollar_impact.toFixed(2)}`)
    return lines.join('\n')
  }).join('\n\n')

  // Build line-item corrections if overcharge data exists
  let lineItemCorrections = ''
  if (result.overcharge?.line_items?.length) {
    lineItemCorrections = '\n\nLINE ITEM CORRECTIONS:\n' + result.overcharge.line_items.map(item => {
      if (item.flagged) {
        return `- "${item.description}": was $${item.charged_amount} — ${item.flag_reason}. Industry context: ${item.industry_context ?? 'use fair market rate'}`
      }
      return `- "${item.description}": $${item.charged_amount} (OK — keep as-is)`
    }).join('\n')
  }

  // ContractGuard red flags with alternative language
  let clauseFixes = ''
  if (result.contract_guard?.red_flags?.length) {
    clauseFixes = '\n\nCLAUSE FIXES:\n' + result.contract_guard.red_flags
      .filter((f: { alternative_language?: string; clause_text?: string }) => f.alternative_language)
      .map((f: { alternative_language?: string; clause_text?: string }) => `- Replace "${f.clause_text}" with: "${f.alternative_language}"`)
      .join('\n')
  }

  const userMessage = `Fix this ${docLabel}.

ANALYSIS SUMMARY:
Score: ${result.screwed_score} (${result.screwed_score_percent}% screwed)
${result.plain_summary}

FLAGS TO FIX:
${flagSummary}
${lineItemCorrections}
${clauseFixes}

Generate a complete corrected ${docLabel} that resolves every issue above. Use placeholder fields (___________) for any personal information not provided. Make it look professional and ready to print.`

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
  })

  const html = message.content[0].type === 'text' ? message.content[0].text : ''

  return NextResponse.json({ html })
}
